changeSetId = "20241212-01"
author = "futurpanda"
description = "Initial root database setup"
database = "root"

# User table
[[operations]]
type = "createTable"
tableName = "user"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true } },
    { name = "username", type = "text" },
    { name = "email", type = "text", constraints = { nullable = false, unique = true } },
    { name = "password", type = "text" },
    { name = "avatar_url", type = "text" },
    { name = "description", type = "text" },
    { name = "type", type = "text", constraints = { nullable = false }, enumValues = ["OWNER", "USER", "CLIENT"] }
]

# API Key table
[[operations]]
type = "createTable"
tableName = "api_key"
columns = [
    { name = "value", type = "text", constraints = { primaryKey = true, nullable = false } },
    { name = "type", type = "text", constraints = { nullable = false }, enumValues = ["PUBLIC", "PRIVATE", "OWNER_UI"] }
]

# Permission table
[[operations]]
type = "createTable"
tableName = "permission"
columns = [
    { name = "id", type = "integer", autoIncrement = true, constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text", constraints = { nullable = false } },
    { name = "type", type = "text", enumValues = ["DATABASE_LEVEL_PERMISSION", "ACTION_LEVEL_PERMISSION"] }
]

# API Key Permission table
[[operations]]
type = "createTable"
tableName = "api_key_permission"
columns = [
    { name = "api_key_id", type = "text", constraints = { nullable = false } },
    { name = "permission_id", type = "integer", constraints = { nullable = false } }
]
foreignKeys = [
    { baseColumnName = "api_key_id", referencedTableName = "api_key", referencedColumnName = "value", constraintName = "fk_api_key_permission_api_key" },
    { baseColumnName = "permission_id", referencedTableName = "permission", referencedColumnName = "id", constraintName = "fk_api_key_permission_permission" }
]
primaryKey = { columnNames = ["api_key_id", "permission_id"] }

# Database table
[[operations]]
type = "createTable"
tableName = "database"
columns = [
    { name = "id", type = "integer", autoIncrement = true, constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text", constraints = { nullable = false, unique = true } }
]

# Database Permission table
[[operations]]
type = "createTable"
tableName = "database_permission"
columns = [
    { name = "database_id", type = "integer", constraints = { nullable = false } },
    { name = "permission_id", type = "integer", constraints = { nullable = false } }
]
foreignKeys = [
    { baseColumnName = "database_id", referencedTableName = "database", referencedColumnName = "id", constraintName = "fk_database_permission_database" },
    { baseColumnName = "permission_id", referencedTableName = "permission", referencedColumnName = "id", constraintName = "fk_database_permission_permission" }
]
primaryKey = { columnNames = ["database_id", "permission_id"] }


# Entity table
[[operations]]
type = "createTable"
tableName = "database_entity"
columns = [
    { name = "id", type = "integer", autoIncrement = true, constraints = { primaryKey = true, nullable = false } },
    { name = "database_id", type = "integer", constraints = { nullable = false } },
    { name = "entity_name", type = "text", constraints = { nullable = false } }
]
foreignKeys = [
    { baseColumnName = "database_id", referencedTableName = "database", referencedColumnName = "id", constraintName = "fk_entity_database" },
]
uniqueConstraints = [
    "database_id", "entity_name"
]

# Entity Attribute table
[[operations]]
type = "createTable"
tableName = "entity_attribute"
columns = [
    { name = "id", type = "integer", autoIncrement = true, constraints = { primaryKey = true, nullable = false } },
    { name = "database_entity_id", type = "integer", constraints = { nullable = false } },
    { name = "name", type = "text", constraints = { nullable = false } },
    { name = "type", type = "text", constraints = { nullable = false } },
    { name = "is_required", type = "integer", constraints = { nullable = false } },
    { name = "is_primary_key", type = "integer", constraints = { nullable = false } }
]
foreignKeys = [
    { baseColumnName = "database_entity_id", referencedTableName = "database_entity", referencedColumnName = "id", constraintName = "fk_entity_attribute_database_entity" }
]