changeSetId = "20250419-02"
author = "futurpanda"
description = "initial database schema"
database = "root"

[[operations]]
type = "createTable"
tableName = "person"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "email", type = "text" },
    { name = "last_name", type = "text" },
    { name = "first_name", type = "text" },
    { name = "date_of_birth", type = "date" },
    { name = "phone_number", type = "text" },
    { name = "zip_code", type = "text" },
    { name = "occupation", type = "text" }
]

[[operations]]
type = "createTable"
tableName = "refresh_token"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "token", type = "text" },
    { name = "client_id", type = "text" },
    { name = "user_id", type = "text" },
    { name = "expires_at", type = "date" },
    { name = "revoked_at", type = "date" }
]
foreignKeys = [
    { baseColumnName = "client_id", referencedTableName = "client", referencedColumnName = "id", constraintName = "fk_client_refresh_token" },
    { baseColumnName = "user_id", referencedTableName = "user", referencedColumnName = "id", constraintName = "fk_user_refresh_token" }
]

[[operations]]
type = "createTable"
tableName = "user"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "email", type = "text" },
    { name = "password", type = "text" },
    { name = "username", type = "text" },
    { name = "avatar_url", type = "text" },
    { name = "description", type = "text" },
    { name = "person_id", type = "integer" }
]
foreignKeys = [
    { baseColumnName = "person_id", referencedTableName = "person", referencedColumnName = "id", constraintName = "fk_user_person" }
]

[[operations]]
type = "createTable"
tableName = "client"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" },
    { name = "redirect_uri", type = "text" },
    { name = "organization_id", type = "integer" }
]
foreignKeys = [
    { baseColumnName = "organization_id", referencedTableName = "organization", referencedColumnName = "id", constraintName = "fk_client_organization" }
]

[[operations]]
type = "createTable"
tableName = "resource"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" },
    { name = "type", type = "text" }
]

[[operations]]
type = "createTable"
tableName = "database"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" },
    { name = "client_id", type = "integer" }
]
foreignKeys = [
    { baseColumnName = "id", referencedTableName = "resource", referencedColumnName = "id", constraintName = "fk_database_resource" }
]

[[operations]]
type = "createTable"
tableName = "document"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "titre", type = "text" },
    { name = "contenu", type = "text" }
]
foreignKeys = [
    { baseColumnName = "id", referencedTableName = "resource", referencedColumnName = "id", constraintName = "fk_document_resource" }
]

[[operations]]
type = "createTable"
tableName = "task"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "content", type = "text" },
    { name = "due_date", type = "text" },
    { name = "priority", type = "text" },
    { name = "progress", type = "number" },
    { name = "created_at", type = "date" },
    { name = "updated_at", type = "date" },
    { name = "deleted_at", type = "date" },
    { name = "completed_at", type = "date" },
    { name = "completed_by", type = "integer" }
]
foreignKeys = [
    { baseColumnName = "completed_by", referencedTableName = "person", referencedColumnName = "id", constraintName = "fk_task_completed_by_person" },
     { baseColumnName = "id", referencedTableName = "resource", referencedColumnName = "id", constraintName = "fk_task_resource" }
]

[[operations]]
type = "createTable"
tableName = "assignee_task"
columns = [
    { name = "person_id", type = "integer", constraints = { nullable = false } },
    { name = "task_id", type = "integer", constraints = { nullable = false } }
]
primaryKey = ["person_id", "task_id"]
foreignKeys = [
    { baseColumnName = "person_id", referencedTableName = "person", referencedColumnName = "id", constraintName = "fk_assignee_task_person" },
    { baseColumnName = "task_id", referencedTableName = "task", referencedColumnName = "id", constraintName = "fk_assignee_task_task" }
]

[[operations]]
type = "createTable"
tableName = "organization"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" },
    { name = "zip_code", type = "text" },
    { name = "vat_number", type = "text" },
    { name = "client_id", type = "integer" }
]
foreignKeys = [
    { baseColumnName = "client_id", referencedTableName = "client", referencedColumnName = "id", constraintName = "fk_organization_client" }
]

[[operations]]
type = "createTable"
tableName = "employee_organization"
columns = [
    { name = "employee_id", type = "integer", constraints = { nullable = false } },
    { name = "organization_id", type = "integer", constraints = { nullable = false } }
]
primaryKey = ["employee_id", "organization_id"]
foreignKeys = [
    { baseColumnName = "employee_id", referencedTableName = "person", referencedColumnName = "id", constraintName = "fk_employee_organization_employee" },
    { baseColumnName = "organization_id", referencedTableName = "organization", referencedColumnName = "id", constraintName = "fk_employee_organization_organization" }
]

[[operations]]
type = "createTable"
tableName = "authorization"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" }
]

[[operations]]
type = "createTable"
tableName = "resource_client_authorization"
columns = [
    { name = "resource_id", type = "integer" },
    { name = "client_id", type = "integer" },
    { name = "authorization_id", type = "integer" }
]
primaryKey = ["resource_id", "client_id", "authorization_id"]
foreignKeys = [
    { baseColumnName = "resource_id", referencedTableName = "resource", referencedColumnName = "id", constraintName = "fk_rca_resource" },
    { baseColumnName = "client_id", referencedTableName = "client", referencedColumnName = "id", constraintName = "fk_rca_client" },
    { baseColumnName = "authorization_id", referencedTableName = "authorization", referencedColumnName = "id", constraintName = "fk_rca_authorization" }
]

[[operations]]
type = "createTable"
tableName = "permission"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" }
]

[[operations]]
type = "createTable"
tableName = "role"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text" }
]

[[operations]]
type = "createTable"
tableName = "user_role"
columns = [
    { name = "user_id", type = "integer", constraints = { nullable = false } },
    { name = "role_id", type = "integer", constraints = { nullable = false } }
]
primaryKey = ["user_id", "role_id"]
foreignKeys = [
    { baseColumnName = "user_id", referencedTableName = "user", referencedColumnName = "id", constraintName = "fk_user_role_user" },
    { baseColumnName = "role_id", referencedTableName = "role", referencedColumnName = "id", constraintName = "fk_user_role_role" }
]

[[operations]]
type = "createTable"
tableName = "role_permission"
columns = [
    { name = "role_id", type = "integer", constraints = {  nullable = false } },
    { name = "permission_id", type = "integer", constraints = {  nullable = false } }
]
primaryKey = ["role_id", "permission_id"]
foreignKeys = [
    { baseColumnName = "role_id", referencedTableName = "role", referencedColumnName = "id", constraintName = "fk_role_permission_role" },
    { baseColumnName = "permission_id", referencedTableName = "permission", referencedColumnName = "id", constraintName = "fk_role_permission_permission" }
]
