changeSetId = "20241212-01"
author = "futurpanda"
description = "Initial root database setup"
database = "root"

# User table
[[operations]]
type = "createTable"
tableName = "user"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true } },
    { name = "username", type = "text" },
    { name = "email", type = "text", constraints = { nullable = false, unique = true } },
    { name = "password", type = "text" },
    { name = "avatar_url", type = "text" },
    { name = "description", type = "text" },
    { name = "type", type = "text", constraints = { nullable = false }, enumValues = ["OWNER", "USER", "CLIENT"] }
]

[[operations]]
type = "createTable"
tableName = "api_key"
columns = [
    { name = "value", type = "text", constraints = { primaryKey = true, nullable = false } },
    { name = "type", type = "text", constraints = { nullable = false }, enumValues = ["PUBLIC", "PRIVATE", "OWNER_UI"] }
]

[[operations]]
type = "createTable"
tableName = "permission"
columns = [
    { name = "id", type = "integer", autoIncrement = true, constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text", constraints = { nullable = false } },
    { name = "type", type = "text", enumValues = ["DATABASE_LEVEL_PERMISSION", "ACTION_LEVEL_PERMISSION"] }
]

[[operations]]
type = "createTable"
tableName = "api_key_permission"
columns = [
    { name = "api_key_id", type = "text", constraints = { nullable = false } },
    { name = "permission_id", type = "integer", constraints = { nullable = false } }
]
foreignKeys = [
    { baseColumnName = "api_key_id", referencedTableName = "api_key", referencedColumnName = "value", constraintName = "fk_api_key_permission_api_key" },
    { baseColumnName = "permission_id", referencedTableName = "permission", referencedColumnName = "id", constraintName = "fk_api_key_permission_permission" }
]
primaryKey =  ["api_key_id", "permission_id"]

[[operations]]
type = "createTable"
tableName = "database"
columns = [
    { name = "id", type = "integer", autoIncrement = true, constraints = { primaryKey = true, nullable = false } },
    { name = "name", type = "text", constraints = { nullable = false, unique = true } },
    { name = "client_id", type = "text", constraints = { nullable = false} }
]
