changeSetId = "20241212-02"
author = "futurpanda"
description = "test"
database = "root"

[[operations]]
type = "createTable"
tableName = "test"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true } },
    { name = "content", type = "text" },
]

