changeSetId = "20250205-01"
author = "futurpanda"
description = "add oauth tokens"
database = "root"

[[operations]]
type = "createTable"
tableName = "oauth_clients"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true } },
    { name = "name", type = "text", constraints = { notNull = true } },
    { name = "redirect_uri", type = "text", constraints = { notNull = true } },
    { name = "allowed_scopes", type = "text", constraints = { notNull = true } },
    { name = "created_at", type = "timestamp", constraints = { notNull = true } },
    { name = "updated_at", type = "timestamp"  },
]


[[operations]]
type = "createTable"
tableName = "oauth_authorization"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true } },
    { name = "client_id", type = "integer", constraints = { notNull = true } },
    { name = "authorized_scopes", type = "text", constraints = { notNull = true } },
    { name = "created_at", type = "timestamp", constraints = { notNull = true } },
    { name = "updated_at", type = "timestamp"  },
]
foreignKeys = [
    { baseColumnName = "client_id", referencedTableName = "oauth_client", referencedColumnName = "id", constraintName = "fk_oauth_client_authorization_oauth_client" },
]

[[operations]]
type = "createTable"
tableName = "database_permission"
columns = [
    { name = "database_id", type = "integer", constraints = { nullable = false } },
    { name = "oauth_autorization_id", type = "integer", constraints = { nullable = false } }
]
foreignKeys = [
    { baseColumnName = "database_id", referencedTableName = "database", referencedColumnName = "id", constraintName = "fk_database_permission_database" },
    { baseColumnName = "oauth_autorization_id", referencedTableName = "oauth_authorization", referencedColumnName = "id", constraintName = "fk_database_oauth_autorization_id" }
]
primaryKey =  ["database_id", "oauth_autorization_id"]




[[operations]]
type = "createTable"
tableName = "oauth_refresh_token"
columns = [
    { name = "id", type = "integer", constraints = { primaryKey = true } },
    { name = "token", type = "text" , constraints = { notNull = true }  },
    { name = "client_id", type = "text" },
    { name = "user_id", type = "integer"},
    { name = "expires_at", type = "timestamp", constraints = { notNull = true } },
    { name = "revoked_at", type = "timestamp"  },
    { name = "created_at", type = "timestamp", constraints = { notNull = true } , defaultValue = "CURRENT_TIMESTAMP" },
    { name = "updated_at", type = "timestamp"  },
]
foreignKeys = [
    { baseColumnName = "user_id", referencedTableName = "user", referencedColumnName = "id", constraintName = "fk_user_oauth_refresh_token_user" },
]
