-- Generated by Mocodo 4.3.2

CREATE TABLE A (
  PRIMARY KEY (name_1, name_2, name_3),
  name_1 VARCHAR(42) NOT NULL,
  name_2 VARCHAR(42) NOT NULL,
  name_3 VARCHAR(42) NOT NULL
);

CREATE TABLE ACCEDER (
  PRIMARY KEY (name_1, name_2, name_3, name_4),
  name_1 VARCHAR(42) NOT NULL,
  name_2 VARCHAR(42) NOT NULL,
  name_3 VARCHAR(42) NOT NULL,
  name_4 VARCHAR(42) NOT NULL
);

CREATE TABLE Adresse (
  PRIMARY KEY (nom_de_rue),
  nom_de_rue  VARCHAR(42) NOT NULL,
  code_postal VARCHAR(42),
  pays        VARCHAR(42)
);

CREATE TABLE COMPOSER (
  PRIMARY KEY (name_1, name_2),
  name_1 VARCHAR(42) NOT NULL,
  name_2 VARCHAR(42) NOT NULL
);

CREATE TABLE EMPLOYER (
  PRIMARY KEY (nom, name),
  nom  VARCHAR(42) NOT NULL,
  name VARCHAR(42) NOT NULL
);

CREATE TABLE HABITER (
  PRIMARY KEY (name, nom_de_rue),
  name       VARCHAR(42) NOT NULL,
  nom_de_rue VARCHAR(42) NOT NULL
);

CREATE TABLE HAS (
  PRIMARY KEY (name_1, name_2, token),
  name_1 VARCHAR(42) NOT NULL,
  name_2 VARCHAR(42) NOT NULL,
  token  VARCHAR(42) NOT NULL
);

CREATE TABLE LOCALISER (
  PRIMARY KEY (nom_de_rue, nom),
  nom_de_rue VARCHAR(42) NOT NULL,
  nom        VARCHAR(42) NOT NULL
);

CREATE TABLE Refresh_Token (
  PRIMARY KEY (token),
  token      VARCHAR(42) NOT NULL,
  client_id  VARCHAR(42),
  user_id    VARCHAR(42),
  expires_at VARCHAR(42),
  revoked_at VARCHAR(42)
);

CREATE TABLE Resource (
  PRIMARY KEY (name),
  name              VARCHAR(42) NOT NULL,
  type              VARCHAR(42),
  id                VARCHAR(42) NULL,
  contenu           VARCHAR(42) NULL,
  date_limite       VARCHAR(42) NULL,
  assigne_a         VARCHAR(42) NULL,
  priorite          VARCHAR(42) NULL,
  progres           VARCHAR(42) NULL,
  email             VARCHAR(42) NULL,
  nom_de_famille    VARCHAR(42) NULL,
  prenom            VARCHAR(42) NULL,
  date_de_naissance VARCHAR(42) NULL,
  telephone         VARCHAR(42) NULL,
  addresse          VARCHAR(42) NULL,
  code_postal       VARCHAR(42) NULL,
  metier            VARCHAR(42) NULL,
  name_2            VARCHAR(42) NULL
);

CREATE TABLE SITUER_ (
  PRIMARY KEY (nom, nom_de_rue),
  nom        VARCHAR(42) NOT NULL,
  nom_de_rue VARCHAR(42) NOT NULL
);

CREATE TABLE SITUER_ (
  PRIMARY KEY (nom_1, nom_2),
  nom_1 VARCHAR(42) NOT NULL,
  nom_2 VARCHAR(42) NOT NULL
);

ALTER TABLE A ADD FOREIGN KEY (name_2) REFERENCES Personne (name);
ALTER TABLE A ADD FOREIGN KEY (name_1) REFERENCES Personne (name);
ALTER TABLE ACCEDER ADD FOREIGN KEY (name_4) REFERENCES Resource (name);
ALTER TABLE ACCEDER ADD FOREIGN KEY (name_2) REFERENCES Personne (name);
ALTER TABLE ACCEDER ADD FOREIGN KEY (name_1) REFERENCES Personne (name);

ALTER TABLE EMPLOYER ADD FOREIGN KEY (name) REFERENCES Resource (name);

ALTER TABLE HABITER ADD FOREIGN KEY (nom_de_rue) REFERENCES Adresse (nom_de_rue);
ALTER TABLE HABITER ADD FOREIGN KEY (name) REFERENCES Resource (name);

ALTER TABLE HAS ADD FOREIGN KEY (token) REFERENCES Refresh Token (token);
ALTER TABLE HAS ADD FOREIGN KEY (name_2) REFERENCES Personne (name);
ALTER TABLE HAS ADD FOREIGN KEY (name_1) REFERENCES Personne (name);

ALTER TABLE LOCALISER ADD FOREIGN KEY (nom_de_rue) REFERENCES Adresse (nom_de_rue);

ALTER TABLE Resource ADD FOREIGN KEY (name_2) REFERENCES Resource (name);

ALTER TABLE SITUER_ ADD FOREIGN KEY (nom_de_rue) REFERENCES Adresse (nom_de_rue);
