# fly.toml app configuration file generated for futurpanda-sonarqube on 2025-02-08T15:31:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'futurpanda-sonarqube'
primary_region = 'cdg'

[build]

[http_service]
internal_port = 9000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '8gb'
cpu_kind = 'performance'
cpus = 2
kernel_args = ["sysctl.vm.max_map_count=262144"]

[experimental]
kernel_args = [
    "vm.max_map_count=262144",
    "vm.max_file_descriptors=65536"
]