/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedQueryIndexImport } from './routes/_authenticated/query/index'
import { Route as AuthenticatedDatabackupIndexImport } from './routes/_authenticated/databackup/index'
import { Route as AuthenticatedDataIndexImport } from './routes/_authenticated/data/index'
import { Route as AuthenticatedCapletsIndexImport } from './routes/_authenticated/caplets/index'
import { Route as AuthenticatedAccountIndexImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedDatabackupDataSourceIdImport } from './routes/_authenticated/databackup/$dataSourceId'
import { Route as AuthenticatedDataDatabaseIdImport } from './routes/_authenticated/data/$databaseId'
import { Route as AuthenticatedCapletsCapletIdImport } from './routes/_authenticated/caplets/$capletId'
import { Route as AuthenticatedDataDatabaseIdQueryImport } from './routes/_authenticated/data/$databaseId.query'
import { Route as AuthenticatedDataDatabaseIdTableIdImport } from './routes/_authenticated/data/$databaseId.$tableId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedQueryIndexRoute = AuthenticatedQueryIndexImport.update({
  path: '/query/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDatabackupIndexRoute =
  AuthenticatedDatabackupIndexImport.update({
    path: '/databackup/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDataIndexRoute = AuthenticatedDataIndexImport.update({
  path: '/data/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCapletsIndexRoute = AuthenticatedCapletsIndexImport.update({
  path: '/caplets/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAccountIndexRoute = AuthenticatedAccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDatabackupDataSourceIdRoute =
  AuthenticatedDatabackupDataSourceIdImport.update({
    path: '/databackup/$dataSourceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDataDatabaseIdRoute =
  AuthenticatedDataDatabaseIdImport.update({
    path: '/data/$databaseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCapletsCapletIdRoute =
  AuthenticatedCapletsCapletIdImport.update({
    path: '/caplets/$capletId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDataDatabaseIdQueryRoute =
  AuthenticatedDataDatabaseIdQueryImport.update({
    path: '/query',
    getParentRoute: () => AuthenticatedDataDatabaseIdRoute,
  } as any)

const AuthenticatedDataDatabaseIdTableIdRoute =
  AuthenticatedDataDatabaseIdTableIdImport.update({
    path: '/$tableId',
    getParentRoute: () => AuthenticatedDataDatabaseIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/caplets/$capletId': {
      id: '/_authenticated/caplets/$capletId'
      path: '/caplets/$capletId'
      fullPath: '/caplets/$capletId'
      preLoaderRoute: typeof AuthenticatedCapletsCapletIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/data/$databaseId': {
      id: '/_authenticated/data/$databaseId'
      path: '/data/$databaseId'
      fullPath: '/data/$databaseId'
      preLoaderRoute: typeof AuthenticatedDataDatabaseIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/databackup/$dataSourceId': {
      id: '/_authenticated/databackup/$dataSourceId'
      path: '/databackup/$dataSourceId'
      fullPath: '/databackup/$dataSourceId'
      preLoaderRoute: typeof AuthenticatedDatabackupDataSourceIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/caplets/': {
      id: '/_authenticated/caplets/'
      path: '/caplets'
      fullPath: '/caplets'
      preLoaderRoute: typeof AuthenticatedCapletsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/data/': {
      id: '/_authenticated/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/databackup/': {
      id: '/_authenticated/databackup/'
      path: '/databackup'
      fullPath: '/databackup'
      preLoaderRoute: typeof AuthenticatedDatabackupIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/query/': {
      id: '/_authenticated/query/'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AuthenticatedQueryIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/data/$databaseId/$tableId': {
      id: '/_authenticated/data/$databaseId/$tableId'
      path: '/$tableId'
      fullPath: '/data/$databaseId/$tableId'
      preLoaderRoute: typeof AuthenticatedDataDatabaseIdTableIdImport
      parentRoute: typeof AuthenticatedDataDatabaseIdImport
    }
    '/_authenticated/data/$databaseId/query': {
      id: '/_authenticated/data/$databaseId/query'
      path: '/query'
      fullPath: '/data/$databaseId/query'
      preLoaderRoute: typeof AuthenticatedDataDatabaseIdQueryImport
      parentRoute: typeof AuthenticatedDataDatabaseIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDataDatabaseIdRouteChildren {
  AuthenticatedDataDatabaseIdTableIdRoute: typeof AuthenticatedDataDatabaseIdTableIdRoute
  AuthenticatedDataDatabaseIdQueryRoute: typeof AuthenticatedDataDatabaseIdQueryRoute
}

const AuthenticatedDataDatabaseIdRouteChildren: AuthenticatedDataDatabaseIdRouteChildren =
  {
    AuthenticatedDataDatabaseIdTableIdRoute:
      AuthenticatedDataDatabaseIdTableIdRoute,
    AuthenticatedDataDatabaseIdQueryRoute:
      AuthenticatedDataDatabaseIdQueryRoute,
  }

const AuthenticatedDataDatabaseIdRouteWithChildren =
  AuthenticatedDataDatabaseIdRoute._addFileChildren(
    AuthenticatedDataDatabaseIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCapletsCapletIdRoute: typeof AuthenticatedCapletsCapletIdRoute
  AuthenticatedDataDatabaseIdRoute: typeof AuthenticatedDataDatabaseIdRouteWithChildren
  AuthenticatedDatabackupDataSourceIdRoute: typeof AuthenticatedDatabackupDataSourceIdRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedCapletsIndexRoute: typeof AuthenticatedCapletsIndexRoute
  AuthenticatedDataIndexRoute: typeof AuthenticatedDataIndexRoute
  AuthenticatedDatabackupIndexRoute: typeof AuthenticatedDatabackupIndexRoute
  AuthenticatedQueryIndexRoute: typeof AuthenticatedQueryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCapletsCapletIdRoute: AuthenticatedCapletsCapletIdRoute,
  AuthenticatedDataDatabaseIdRoute:
    AuthenticatedDataDatabaseIdRouteWithChildren,
  AuthenticatedDatabackupDataSourceIdRoute:
    AuthenticatedDatabackupDataSourceIdRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedCapletsIndexRoute: AuthenticatedCapletsIndexRoute,
  AuthenticatedDataIndexRoute: AuthenticatedDataIndexRoute,
  AuthenticatedDatabackupIndexRoute: AuthenticatedDatabackupIndexRoute,
  AuthenticatedQueryIndexRoute: AuthenticatedQueryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/caplets/$capletId': typeof AuthenticatedCapletsCapletIdRoute
  '/data/$databaseId': typeof AuthenticatedDataDatabaseIdRouteWithChildren
  '/databackup/$dataSourceId': typeof AuthenticatedDatabackupDataSourceIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/caplets': typeof AuthenticatedCapletsIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/databackup': typeof AuthenticatedDatabackupIndexRoute
  '/query': typeof AuthenticatedQueryIndexRoute
  '/data/$databaseId/$tableId': typeof AuthenticatedDataDatabaseIdTableIdRoute
  '/data/$databaseId/query': typeof AuthenticatedDataDatabaseIdQueryRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/caplets/$capletId': typeof AuthenticatedCapletsCapletIdRoute
  '/data/$databaseId': typeof AuthenticatedDataDatabaseIdRouteWithChildren
  '/databackup/$dataSourceId': typeof AuthenticatedDatabackupDataSourceIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/caplets': typeof AuthenticatedCapletsIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/databackup': typeof AuthenticatedDatabackupIndexRoute
  '/query': typeof AuthenticatedQueryIndexRoute
  '/data/$databaseId/$tableId': typeof AuthenticatedDataDatabaseIdTableIdRoute
  '/data/$databaseId/query': typeof AuthenticatedDataDatabaseIdQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/caplets/$capletId': typeof AuthenticatedCapletsCapletIdRoute
  '/_authenticated/data/$databaseId': typeof AuthenticatedDataDatabaseIdRouteWithChildren
  '/_authenticated/databackup/$dataSourceId': typeof AuthenticatedDatabackupDataSourceIdRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/caplets/': typeof AuthenticatedCapletsIndexRoute
  '/_authenticated/data/': typeof AuthenticatedDataIndexRoute
  '/_authenticated/databackup/': typeof AuthenticatedDatabackupIndexRoute
  '/_authenticated/query/': typeof AuthenticatedQueryIndexRoute
  '/_authenticated/data/$databaseId/$tableId': typeof AuthenticatedDataDatabaseIdTableIdRoute
  '/_authenticated/data/$databaseId/query': typeof AuthenticatedDataDatabaseIdQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/caplets/$capletId'
    | '/data/$databaseId'
    | '/databackup/$dataSourceId'
    | '/account'
    | '/caplets'
    | '/data'
    | '/databackup'
    | '/query'
    | '/data/$databaseId/$tableId'
    | '/data/$databaseId/query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/caplets/$capletId'
    | '/data/$databaseId'
    | '/databackup/$dataSourceId'
    | '/account'
    | '/caplets'
    | '/data'
    | '/databackup'
    | '/query'
    | '/data/$databaseId/$tableId'
    | '/data/$databaseId/query'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/caplets/$capletId'
    | '/_authenticated/data/$databaseId'
    | '/_authenticated/databackup/$dataSourceId'
    | '/_authenticated/account/'
    | '/_authenticated/caplets/'
    | '/_authenticated/data/'
    | '/_authenticated/databackup/'
    | '/_authenticated/query/'
    | '/_authenticated/data/$databaseId/$tableId'
    | '/_authenticated/data/$databaseId/query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/caplets/$capletId",
        "/_authenticated/data/$databaseId",
        "/_authenticated/databackup/$dataSourceId",
        "/_authenticated/account/",
        "/_authenticated/caplets/",
        "/_authenticated/data/",
        "/_authenticated/databackup/",
        "/_authenticated/query/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/caplets/$capletId": {
      "filePath": "_authenticated/caplets/$capletId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/$databaseId": {
      "filePath": "_authenticated/data/$databaseId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/data/$databaseId/$tableId",
        "/_authenticated/data/$databaseId/query"
      ]
    },
    "/_authenticated/databackup/$dataSourceId": {
      "filePath": "_authenticated/databackup/$dataSourceId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/account/": {
      "filePath": "_authenticated/account/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/caplets/": {
      "filePath": "_authenticated/caplets/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/": {
      "filePath": "_authenticated/data/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/databackup/": {
      "filePath": "_authenticated/databackup/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/query/": {
      "filePath": "_authenticated/query/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/$databaseId/$tableId": {
      "filePath": "_authenticated/data/$databaseId.$tableId.tsx",
      "parent": "/_authenticated/data/$databaseId"
    },
    "/_authenticated/data/$databaseId/query": {
      "filePath": "_authenticated/data/$databaseId.query.tsx",
      "parent": "/_authenticated/data/$databaseId"
    }
  }
}
ROUTE_MANIFEST_END */
