name: Deploy DEV 
on:
  push:
    branches: [ dev ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy_hero:
    name: Deploy Dev Hero Website to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy 
        run: flyctl deploy ./packages/www -c fly.dev.toml
        
  deploy_capsule:
    name: Deploy Dev Capsule To Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy 
        run: flyctl deploy ./packages/server -c fly.dev.toml

