name: Deploy DEV 
on:
  push:
    branches: [ dev ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy Dev Services to Fly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['hero', 'capsule', 'capsule-kit']
        include:
          - service: hero
            path: ./packages/www
            config: -c fly.dev.toml
          - service: capsule
            path: ./packages/server
            config: -c fly.dev.toml
          - service: capsule-kit
            path: ./packages/capsule-kit
            config: -c fly.dev.toml
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy ${{ matrix.service }}
        run: flyctl deploy ${{ matrix.path }} ${{ matrix.config }}

      - name: Verify deployment
        run: flyctl status ${{ matrix.path }} ${{ matrix.config }}
