name: Push Docker Image Server DEV

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"

      - name: login to hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: futurpanda/capsule

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: futurpanda/capsule:latest
          labels: ${{ steps.meta.outputs.labels }}
