name: Push Docker Image Server

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: futurpanda/capsule
          
      - name: Install shared-types (package)
        run: npm install && npm run build
        working-directory: ./packages/shared-types
        
      - name: Install chisel (package)
        run: npm install && npm run build
        working-directory: ./packages/chisel

      - name: Build and push dev image
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v4
        with:
          context: ./packages/server
          push: true
          tags: futurpanda/capsule-back-dev:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push main image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: ./packages/server
          push: true
          tags: futurpanda/capsule-back:latest
          labels: ${{ steps.meta.outputs.labels }}
          
      #- name: Build and push to capsule repository
       # uses: docker/build-push-action@v4
        #with:
        #  context: .
        #  push: true
        #  tags: futurpanda/capsule:latest
        #  labels: ${{ steps.meta.outputs.labels }}
