name: Deploy Prod
on:
  push:
    branches: [ "main" ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy_hero:
    name: Deploy Prod Hero Website to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy ./packages/www
        
  deploy_capsule:
    name: Deploy Prod Capsule To Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy 
        run: flyctl deploy ./packages/server -c fly.dev.toml
